name: Gear Host

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Jekyll build
        run: jekyll build      

      - name: GearHost Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftp.gear.host/site/wwwroot/
          ftp-username: ${{ secrets.GEAR_USER }} 
          ftp-password: ${{ secrets.GEAR_PW }} 
          local-dir: ./_site/
          

        